모든 태그 및 태그 정보 가져오기 API 추가
Beering-KUIT/Beering-Server pull request #58
Opened 2024-02-05 13:29 UTC by YoonSubLim

## PR 타입
- [x] 기능 추가
- [ ] 기능 삭제
- [ ] 버그 수정
- [ ] 리팩토링
- [ ] 파일 혹은 폴더명 수정
- [ ] 파일 혹은 폴더 삭제
- [ ] 기타 : 

### 작업 동기
태그 관련 API 추가

## 변경 사항
- 태그 상세보기
화면에 들어가는 태그 에 대한 상세정보 (tagId 에 해당하는 tagName 과 description return) API 추가
태그 상세정보에서 표시되는 태그 기반 주류 리스트는, 주류 검색 API 를 사용할 것이라 구현 X
- 모든 태그 받아오기
주류 검색 필터에서 표시할 모든 주류 태그 반환하는 API 추가

### 주안점
전반적인 구조..?

### 설명
위와 같음

## 체크리스트
- [x] 무엇을 변경했는지 충분히 설명하고 있나요?
- [x] 새로운 기술을 사용했다면, 그 기술을 설명하고 있나요?
- [x] 이해하기 어려운 비즈니스 로직에 관해서 부연 설명을 하고 있나요?

2024-02-05 15:52 UTC, JooeonLee approved these changes
확인했습니다!

2024-02-06 07:58 UTC, kwiyoon commented
수고하셨습니당!!

2024-02-06 08:00 UTC, kwiyoon approved these changes

2024-02-06 14:38 UTC, hamhyeongju commented on src/main/java/kuit/project/beering/service/TagService.java
> +        }
Optional의 orElseThrow() 를 사용하는게 좋을 것 같습니다.
Tag 도메인에 대한 예외를 정의(BaseResponseStatus에 관련 값 생성)하여 throw 하고 이를 GlobalControllerAdvice 에서 처리하는 방식으로 예외를 핸들링할 수 있습니다. -> 이 부분에서 이해가 잘 안되는 플로우 있으면 질문 주세요.
Optional을 사용하는데 null을 반환하는 것은 의미가 없는 행위인 것 같아요.
아래 블로그 읽어보시면 도움 될 것 같습니다.
https://velog.io/@taebong98/Optional-%EC%95%88%ED%8B%B0%ED%8C%A8%ED%84%B4

2024-02-06 15:05 UTC, hamhyeongju requested changes
코멘트 남긴 부분 수정되면 알려주세요~

2024-02-06 16:11 UTC, YoonSubLim commented on src/main/java/kuit/project/beering/service/TagService.java
> +        }
DomainException 상속받는 TagException 추가했습니다.
Optional orElseThrow TagException 하고,
GlobalControllerAdvice 내 DomainException Handler 에서 처리되도록 코드 변경했습니다 !

2024-02-07 07:01 UTC, hamhyeongju approved these changes

2024-02-07 07:01 UTC, merged